#!/bin/sh

# shellcheck disable=SC1091,SC3043,SC3010,SC3037

. "/lib/functions.sh"

# shellcheck source=../secrets
. "/etc/secrets"

sdcard="/mnt/mmcblk0p1"
set -e

uci set ksmbd.sdcard="share"
uci set ksmbd.sdcard.name="sdcard"
uci set ksmbd.sdcard.path="$sdcard"
uci set ksmbd.sdcard.read_only="yes"
uci set ksmbd.sdcard.writable="root"
uci set ksmbd.sdcard.guest_ok="yes"
uci commit ksmbd
ksmbd.adduser -a -p "$PASSWORD" "root"
