#!/bin/sh

# shellcheck disable=SC1091,SC3043,SC3010,SC3037

. "/lib/functions.sh"

# shellcheck source=../secrets
. "/etc/secrets"

sdcard="/mnt/mmcblk0p1"

set -e

uci set transmission.@transmission[0].enabled="1"
uci set transmission.@transmission[0].encryption="1"
uci set transmission.@transmission[0].download_dir="$sdcard/transmission/downloads"
uci set transmission.@transmission[0].incomplete_dir="$sdcard/transmission/downloading"
uci set transmission.@transmission[0].incomplete_dir_enabled="true"
uci set transmission.@transmission[0].lpd_enabled="true"
uci set transmission.@transmission[0].rpc_authentication_required="true"
uci set transmission.@transmission[0].rpc_bind_address="192.168.8.1"
uci set transmission.@transmission[0].rpc_whitelist="127.0.0.1,192.168.8.*"
uci set transmission.@transmission[0].rpc_whitelist_enabled="true"
uci set transmission.@transmission[0].rpc_username="transmission"
uci set transmission.@transmission[0].rpc_password="$PASSWORD"
uci commit transmission
